---
kind: pipeline
type: docker
name: node20

steps:
  - name: deploy-production
    image: node:20
    environment:
      SSH_KEY:
        from_secret: DEPLOYMENT_SSH_KEY
    commands:
      - 'echo "$SSH_KEY" > /tmp/ssh_key'
      - chmod 600 /tmp/ssh_key
      - ssh -4 -i /tmp/ssh_key www@caffeine.csclub.uwaterloo.ca -o StrictHostKeyChecking=no '~/bin/classprofile/deploy-2024.sh'
    when:
      branch:
        - main
trigger:
  event:
    exclude:
      - pull_request
