---
kind: pipeline
type: docker
name: node20

steps:
  # - name: install-deps
  #   image: node:20
  #   commands:
  #     - npm install
  # - name: lint
  #   image: node:20
  #   depends_on:
  #     - install-deps
  #   commands:
  #     - npm run lint
  # - name: build
  #   image: node:20
  #   depends_on:
  #     - install-deps
  #   commands:
  #     - npm run build
  - name: deploy-production
    image: node:20
    # depends_on:
    #   - build
    environment:
      SSH_KEY:
        from_secret: DEPLOYMENT_SSH_KEY
    commands:
      - 'echo "$SSH_KEY" > /tmp/ssh_key'
      - chmod 600 /tmp/ssh_key
      - ssh -4 -i /tmp/ssh_key www@caffeine.csclub.uwaterloo.ca -o StrictHostKeyChecking=no '~/bin/classprofile/deploy-2023.sh'
    when:
      branch:
        - main
trigger:
  event:
    exclude:
      - pull_request # avoid double build on PRs
