export const Color = {
  lightNavy: "var(--light-navy)",
  pink: "var(--pink)",
  lightPink: "var(--light-pink)",
  lighterPink: "var(--lighter-pink)",
  darkPink: "var(--dark-pink)",
  darkerPink: "var(--darker-pink)",
  orange: "var(--orange)",
  lightOrange: "var(--light-orange)",
  lighterOrange: "var(--lighter-orange)",
  primaryText: "var(--primary-text)",
  white: "white",
  chartBlueLight: "var(--chart-blue-light)",
  chartBlueHeavy: "var(--chart-blue-heavy)",
  chartYellowLight: "var(--chart-yellow-light)",
  chartYellowHeavy: "var(--chart-yellow-heavy)",
  chartGreenLight: "var(--chart-green-light)",
  chartGreenHeavy: "var(--chart-green-heavy)",
  chartPinkLight: "var(--chart-pink-light)",
  chartPinkHeavy: "var(--chart-pink-heavy)",
  pageBackgroundStart: "var(--page-background-start)",
  pageBackgroudEnd: "var(--page-background-end)",
} as const;
